"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

from dotenv import load_dotenv
load_dotenv()

from  os import getenv, path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 3d parties
    'rest_framework',
    'djoser',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'django_db_logger',
    'accounts',
    'roles',    

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'
LANGUAGE_COOKIE_NAME = 'lang'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'
AUTH_USER_MODEL = 'accounts.User'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE':getenv('ENGINE'),
        'NAME':getenv('NAME'),
        'USER':getenv('USER'),
        'PASSWORD':getenv('PASSWORD'),
        'HOST':getenv('HOST'),
        'PORT':getenv('PORT'),
    }
}

ORCL_IP         = getenv('ORCL_IP')
ORCL_PORT       = getenv('ORCL_PORT')
ORCL_SCHEMA     = getenv('ORCL_SCHEMA')
ORCL_USERNAME   = getenv('ORCL_USERNAME')
ORCL_PASSWORD   = getenv('ORCL_PASSWORD')
###############################################

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


USE_L10N = True

# Supported languages
LANGUAGES = [
    ('ar', 'Arabic'),
    ('en', 'English'),
]

# Translation files location
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.CustomJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}


DJOSER = {
    #'PASSWORD_RESET_CONFIRM_URL': 'password-reset/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': False,
    #'ACTIVATION_URL': 'activation/{uid}/{token}',
    'USER_CREATE_PASSWORD_RETYPE': True,
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    'TOKEN_MODEL': None,
}


AUTH_COOKIE = 'access'
AUTH_COOKIE_REFRESH = 'refresh'
AUTH_COOKIE_HTTP_ONLY = True
AUTH_COOKIE_SECURE = False   # True على production مع https
AUTH_COOKIE_SAMESITE = 'Lax' # أو 'None' لو cross-site
AUTH_COOKIE_PATH = '/'
AUTH_COOKIE_MAX_AGE = 60 * 60 * 24 * 7

SESSION_COOKIE_SECURE = False  # Set to False for development
SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'Lax'  # Or 'None' if using cross-origin
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'

# Allow credentials for cross-origin requests
CORS_ALLOW_CREDENTIALS = True


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True, # genrates a new refresh token after lifetime ends
    "BLACKLIST_AFTER_ROTATION": True, # makes the old token blacklisted after its life time
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(days=7),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=7),

    #"TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_OBTAIN_SERIALIZER": "accounts.serializers.CustomTokenObtainPairSerializer ",

    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.CustomTokenObtainPairSerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",

}



if DEBUG:
    STATIC_URL = 'static/'
    STATIC_ROOT = path.join(BASE_DIR, 'static')

    MEDIA_URL = 'media/'

else:
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'

    STATIC_ROOT = path.join(BASE_DIR, 'staticfiles')

    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

MEDIA_ROOT = path.join(BASE_DIR, 'media')




DOMAIN = getenv('DOMAIN')
CORS_ALLOWED_ORIGINS    = getenv('CORS_ALLOWED_ORIGINS').split(',')
CSRF_TRUSTED_ORIGINS    = getenv('CORS_ALLOWED_ORIGINS').split(',')
CORS_ALLOW_CREDENTIALS  = True


SMS_URL                 = "https://api.unifonic.com/rest/Messages/Send"
SMS_SENDER_ID           = getenv('SMS_SENDER_ID')
SMS_USERNAME            = getenv('SMS_USERNAME')
SMS_PASSWORD            = getenv('SMS_PASSWORD')
SMS_APPSID              = getenv('SMS_APPSID')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#######################    LOGS     #####################
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,

#     'handlers': {
#         'db': {
#             'level': 'ERROR',  # store only warnings + errors in DB
#             'class': 'django_db_logger.db_log_handler.DatabaseLogHandler',
#         },
#         'console': {
#             'level': 'DEBUG',  # show everything in console
#             'class': 'logging.StreamHandler',
#         },
#     },

#     'loggers': {
#         '': {  # root logger
#             'handlers': ['console'],  # console gets all logs
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#         'django': {
#             'handlers': ['console', 'db'],  
#             'level': 'DEBUG',
#             'propagate': False,
#         },
#         # Optional: if you want to log your own app separately
#         'myapp': {
#             'handlers': ['console', 'db'],
#             'level': 'DEBUG',
#             'propagate': False,
#         },
#     },
# }




CELERY_BROKER_URL = getenv('REDIS_SERVER', "redis://127.0.0.1:6380/0")
CELERY_RESULT_BACKEND = getenv('REDIS_SERVER', "redis://127.0.0.1:6380/0")


CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TRACK_STARTED = True
CELERY_SEND_EVENTS = True


